#coding=utf-8

HORIZONTAL = "horizontal"
VERTICAL = "vertical"
IMAGE_EXTENSION = ".png"
COUNTER_PATH = "numbers/"
FLOOR_IMAGE = "floor"
X_COUNTERS = 700    
Y_COUNTERS = 400
SCREEN_WIDTH = 1024
SCREEN_HEIGHT = 768
THROW = "THROW"

